default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DATABASE_POOL_SIZE") { 5 } %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>

development:
  <<: *default
  database: jerb-board_development

test:
  <<: *default
  database: jerb-board_test

production:
  <<: *default
